build:
	gcc-11 -Wall -std=c99 ./example.c -o example.exec
build1:
	gcc-11 -Wall -std=c99 ./example1.c -o example1.exec 
build2:
	gcc-11 -Wall -std=c99 ./example2.c -o example2.exec
build3:
	gcc-11 -Wall -std=c99 ./example3.c -o example3.exec


run:
	./example.exec
run1:
	./example1.exec
run2:
	./example2.exec
run3:
	./example3.exec

clean:
	rm ./*.exec